"""revert previous

Revision ID: c7d386291ede
Revises: f41d1b75d9fa
Create Date: 2023-01-01 08:37:01.509163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7d386291ede'
down_revision = 'f41d1b75d9fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
