"""testing convert string to integer

Revision ID: f41d1b75d9fa
Revises: 492c0abbab4e
Create Date: 2023-01-01 08:25:11.417179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f41d1b75d9fa'
down_revision = '492c0abbab4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
